# Introducción a la programación estadística con R

## Juan Esteban Mejía Velásquez

Antes que todo aprenderemos a lidiar con el directorio de trabajo (workspace). Ya que en este se alojarán nuestros objetos (vectores, matrices, data frames, listeas etc.). En este es donde R leerá nuestros datos y en donde guardará los resultados por defaul.

Para las personas que provengan del manejo de software en donde atreves de una interface de usuario carga sus datos y guardan sus resultados quizá encuentre en sección tediosa.  E directorio de trabajo en realidad es una forma de trabajar organizado de nuestros proyectos. También ha posibilidades de trabajar con importando y exportando sin un directorio de trabajo que veremos más adelante.



### 1.1 Funciones para el manejo del directorio de trabajo de R

In [1]:
getwd() # Nos devuelve el director de trabajo actual en el que esta R

[1] "C:/Users/acer"

In [8]:
ls()  # Lista los objetos del directoro de trabajo actua. Luego miraremos que es un ‘objeto’

character(0)

Como se ve aun no tenemos ningún objeto. Definamos una variables y miremos de nuevo nuestros objetos

In [10]:
Dinero  = 9999999999999
Interes = 0.4
ls()

[1] "Dinero"  "Interes"

In [11]:
# rm(objeto) Remueve (borra) ono o más objetos
rm(Interes)
ls()

[1] "Dinero"

In [2]:
# options() # Permite ver y ajustar las opciones del direrectorio de trbajo.
# Míremoslas

In [1]:
# Help(‘función’) nos lleva hacia la documentación de R acerca dicha función
# Meremos que nos dice a documentación acerca de la función option() para ajustar algunas opciones
# help(options)

Por ejemplo, le podemos indicar que cuando se impriman numero solo muestre cierta cantidad de dígitos. Con digit=’#’ lo hacemos. También le podemos cambiar el promt ‘>’ mednaite : prompt="la forma que queremos"

Pruebe el siguiente código en una consola de R directamente

In [27]:
10/3
options(digits=4, prompt="R>")
10/3

[1] 3.333

[1] 3.333

Lo siguiente nos permitirá dimensionar la salida de los gráficos. Ello lo estaremos utilizando constantemente para mejorar la visualización de este tutorial. 

options(repr.plot.width=7, repr.plot.height=5

widht ajusta aplitud
height ajusta altura

COntinuara --------

### Diferencias entre '<-'. '=' y 'assign()'

### 1.2 Diferencias entre tipos de datos

In [10]:
 x <- 16

In [13]:
class(x)

[1] "numeric"

In [14]:
is.numeric(x)

[1] TRUE

In [22]:
y <- 16L  # L significa que es in'integre' (Entero)

In [23]:
y

[1] 16

In [24]:
class(y)
is.integer(y)

[1] "integer"

[1] TRUE

In [26]:
d <- 'datos'

In [28]:
class(d) # "character" significa datos tipo texto o 'string'

[1] "character"

In [137]:
d <-factor('datos')
d
print(d)


[1] datos
Levels: datos

[1] datos
Levels: datos


In [64]:
t <- TRUE
class(t)
is.logical(t)

[1] "logical"

[1] TRUE

In [67]:
f <- F
class(f)
t*29
f*3454466

[1] "logical"

[1] 29

[1] 0

In [69]:
5 == 7
5 != 7
5 <  7
5 <= 7
'datos' == 'estadistica'
'datos' <  'estadistica'

[1] FALSE

[1] TRUE

[1] TRUE

[1] TRUE

[1] FALSE

[1] TRUE

In [76]:
nchar('datos')
nchar('estadistica')

[1] 5

[1] 11

In [40]:
fecha1<-as.Date('2016-01-26') # Recuerde que Date comienza en mayuscula
fecha1
class(fecha1)

[1] "2016-01-26"

[1] "Date"

In [41]:
as.numeric(fecha1)

[1] 16826

In [60]:
fecha2 <- as.POSIXct('2016-01-26')
fecha2
class(fecha2)

[1] "2016-01-26 COT"

[1] "POSIXct" "POSIXt"

In [61]:
fecha3 <- as.POSIXct('2016-01-26 9:04')
fecha3
class(fecha3)
as.numeric(fecha3)

[1] "2016-01-26 09:04:00 COT"

[1] "POSIXct" "POSIXt"

[1] 1453817040

### Vectores

Vectores son muy similares a los array de otros lenguajes. Son contenedores de multiples elementos de mismo tipo

Operaciones mas eficientes en vectores que en loops

In [77]:
x <- c(1,2,3,4,5)
x

[1] 1 2 3 4 5

In [139]:
x*5
x+5
x/5

[1]  5 10 15 20 25

[1]  6  7  8  9 10

[1] 0.2 0.4 0.6 0.8 1.0

In [84]:
x<-1:5
x

[1] 1 2 3 4 5

In [86]:
5:1
-5:5

[1] 5 4 3 2 1

[1] -5 -4 -3 -2 -1  0  1  2  3  4  5

In [87]:
y <- 5:1
y

[1] 5 4 3 2 1

In [88]:
x+y
x-y
x*y
x/y

[1] 6 6 6 6 6

[1] -4 -2  0  2  4

[1] 5 8 9 8 5

[1] 0.2 0.5 1.0 2.0 5.0

In [90]:
length(x)
length(y)
length(x+y)

[1] 5

[1] 5

[1] 5

In [91]:
x + c(1, 2)


Warning message:
In x + c(1, 2): longitud de objeto mayor no es múltiplo de la longitud de uno menor

[1] 2 4 4 6 6

In [92]:
x < 3

[1]  TRUE  TRUE FALSE FALSE FALSE

In [93]:
any(x < 3)
all(x < 3)

[1] TRUE

[1] FALSE

In [140]:
materias <- c('micro', 'macro', 'desarrollo', NA ,'micro', 'calculo', 'dinamica', 'historia', 
               'desarrollo', 'econometria', NA)
materias

[1] "micro"       "macro"       "desarrollo"  NA            "micro"      
 [6] "calculo"     "dinamica"    "historia"    "desarrollo"  "econometria"
[11] NA

In [141]:
nchar(materias)

[1]  5  5 10  2  5  7  8  8 10 11  2

In [142]:
length(materias)

[1] 11

In [143]:
materias[1]

[1] "micro"

In [144]:
materias[1:3]
materias[-1]
materias[-1:-3]

[1] "micro"      "macro"      "desarrollo"

[1] "macro"       "desarrollo"  NA            "micro"       "calculo"    
 [6] "dinamica"    "historia"    "desarrollo"  "econometria" NA

[1] NA            "micro"       "calculo"     "dinamica"    "historia"   
[6] "desarrollo"  "econometria" NA

In [112]:
materias[c(1, 9)]
materias[c(-1, -9)]

[1] "micro"       "econometria"

[1] "macro"      "desarrollo" "micro"      "calculo"    "dinamica"  
[6] "historia"   "desarrollo"

In [129]:
c(Juan='micro','macro', Laura='econometria')

Juan                       Laura 
      "micro"       "macro" "econometria"

In [131]:
m <- c('micro', 'macro', 'econometria')
m

[1] "micro"       "macro"       "econometria"

In [133]:
names(m) <- c('Juan',2 , 'Laura')
m

Juan             2         Laura 
      "micro"       "macro" "econometria"

In [136]:
materiasF <- factor(materias)
print(materiasF)
materiasF

[1] micro       macro       desarrollo  micro       calculo     dinamica   
[7] historia    desarrollo  econometria
Levels: calculo desarrollo dinamica econometria historia macro micro


[1] micro       macro       desarrollo  micro       calculo     dinamica   
[7] historia    desarrollo  econometria
Levels: calculo desarrollo dinamica econometria historia macro micro

In [138]:
as.numeric(materiasF)

[1] 7 6 2 7 1 3 5 2 4

In [145]:
is.na(materias)

[1] FALSE FALSE FALSE  TRUE FALSE FALSE FALSE FALSE FALSE FALSE  TRUE

### Llamada de funciones


In [148]:
x <-rnorm(50)
x

[1] -1.328321686 -1.381935529 -1.908982952  0.705877191 -0.795249283
 [6]  0.143613133 -1.068957111 -0.480934359 -0.832450769 -0.278939214
[11] -1.156288367  0.710792556  0.458249764 -0.420705968  0.825498637
[16]  2.231657976  0.068432080 -0.697711864 -0.353329773 -2.472016363
[21] -0.079918505 -0.335975283 -0.789890695  0.524571377  0.003558641
[26] -0.385628355 -2.255099314 -0.298398469 -0.176784449 -0.220167625
[31]  1.063033448 -0.352595445 -0.362944284  0.563108287 -0.644629863
[36]  1.443745302 -1.463779490 -0.136042576 -1.636943256  0.187106336
[41]  0.533710447 -0.399860540 -0.581996629 -1.051972175  0.178314613
[46] -1.449201495  0.892527614 -0.334362204 -0.565718587  0.241839411

In [149]:
mean(x)
sd(x)

[1] -0.3184419

[1] 0.9144148

In [152]:
x[c(1, 13, 27)] <- NA
x

[1]           NA -1.381935529 -1.908982952  0.705877191 -0.795249283
 [6]  0.143613133 -1.068957111 -0.480934359 -0.832450769 -0.278939214
[11] -1.156288367  0.710792556           NA -0.420705968  0.825498637
[16]  2.231657976  0.068432080 -0.697711864 -0.353329773 -2.472016363
[21] -0.079918505 -0.335975283 -0.789890695  0.524571377  0.003558641
[26] -0.385628355           NA -0.298398469 -0.176784449 -0.220167625
[31]  1.063033448 -0.352595445 -0.362944284  0.563108287 -0.644629863
[36]  1.443745302 -1.463779490 -0.136042576 -1.636943256  0.187106336
[41]  0.533710447 -0.399860540 -0.581996629 -1.051972175  0.178314613
[46] -1.449201495  0.892527614 -0.334362204 -0.565718587  0.241839411

In [153]:
mean(x)

[1] NA

In [154]:
mean(x, na.rm = T)

[1] -0.272275

Agregar pantallazo de la selecion con tab en Rstudio

In [155]:
summary(x)

   Min. 1st Qu.  Median    Mean 3rd Qu.    Max.    NA's 
-2.4720 -0.7438 -0.3360 -0.2723  0.1827  2.2320       3 

### Otras estructuras de datos en R

### Data Frames

In [166]:
materias
x <- round(runif(11,0, 5), 2)
x
nombres <- c('Esteban', 'Laura', 'Andrea', 'Nicolas')
y <- sample(size = 11, x = nombres, replace = T)
y

[1] "micro"       "macro"       "desarrollo"  NA            "micro"      
 [6] "calculo"     "dinamica"    "historia"    "desarrollo"  "econometria"
[11] NA

[1] 4.87 0.51 1.81 1.64 0.91 3.11 0.45 0.49 4.56 0.48 1.48

[1] "Andrea"  "Nicolas" "Nicolas" "Esteban" "Nicolas" "Laura"   "Laura"  
 [8] "Laura"   "Laura"   "Nicolas" "Laura"

In [170]:
datos.df <- data.frame(materias, x, y)
datos.df

materias    x       y
1        micro 4.87  Andrea
2        macro 0.51 Nicolas
3   desarrollo 1.81 Nicolas
4         <NA> 1.64 Esteban
5        micro 0.91 Nicolas
6      calculo 3.11   Laura
7     dinamica 0.45   Laura
8     historia 0.49   Laura
9   desarrollo 4.56   Laura
10 econometria 0.48 Nicolas
11        <NA> 1.48   Laura

In [180]:
names(datos.df)
rownames(datos.df)

[1] "Materias"   "Notas"      "Estudiante"

[1] "1"  "2"  "3"  "4"  "5"  "6"  "7"  "8"  "9"  "10" "11"

In [183]:
prefijo='id'
sufijo=seq(from=1, to=11)
rownames(datos.df) <- paste(prefijo, sufijo, sep='-' )
datos.df

Materias Notas Estudiante
id-1        micro  4.87     Andrea
id-2        macro  0.51    Nicolas
id-3   desarrollo  1.81    Nicolas
id-4         <NA>  1.64    Esteban
id-5        micro  0.91    Nicolas
id-6      calculo  3.11      Laura
id-7     dinamica  0.45      Laura
id-8     historia  0.49      Laura
id-9   desarrollo  4.56      Laura
id-10 econometria  0.48    Nicolas
id-11        <NA>  1.48      Laura

In [ ]:
rownames(datos.df) <- c(rep())

In [173]:
names(datos.df) <- c('Materias', 'Notas', 'Estudiante')
datos.df


Materias Notas Estudiante
1        micro  4.87     Andrea
2        macro  0.51    Nicolas
3   desarrollo  1.81    Nicolas
4         <NA>  1.64    Esteban
5        micro  0.91    Nicolas
6      calculo  3.11      Laura
7     dinamica  0.45      Laura
8     historia  0.49      Laura
9   desarrollo  4.56      Laura
10 econometria  0.48    Nicolas
11        <NA>  1.48      Laura

In [188]:
datos.df$Estudiante

[1] Andrea  Nicolas Nicolas Esteban Nicolas Laura   Laura   Laura   Laura  
[10] Nicolas Laura  
Levels: Andrea Esteban Laura Nicolas

In [164]:
class(datos.df)
class(datos.df$materias)
class(datos.df$x)
class(datos.df$y)

[1] "data.frame"

[1] "factor"

[1] "numeric"

[1] "factor"

In [165]:
str(datos.df)

'data.frame':	11 obs. of  3 variables:
 $ materias: Factor w/ 7 levels "calculo","desarrollo",..: 7 6 2 NA 7 1 3 5 2 4 ...
 $ x       : num  1.06 1.7 1.3 1.49 4.11 2.52 3.78 2 3.28 2.64 ...
 $ y       : Factor w/ 5 levels "Andrea","Esteban",..: 3 5 4 4 5 1 2 2 5 2 ...


In [175]:
datos.df2 <- data.frame(Materias=materias, Notas=x, Estudinte=y, stringsAsFactors = F)
datos.df2
str(datos.df2)

Materias Notas Estudinte
1        micro  4.87    Andrea
2        macro  0.51   Nicolas
3   desarrollo  1.81   Nicolas
4         <NA>  1.64   Esteban
5        micro  0.91   Nicolas
6      calculo  3.11     Laura
7     dinamica  0.45     Laura
8     historia  0.49     Laura
9   desarrollo  4.56     Laura
10 econometria  0.48   Nicolas
11        <NA>  1.48     Laura

'data.frame':	11 obs. of  3 variables:
 $ Materias : chr  "micro" "macro" "desarrollo" NA ...
 $ Notas    : num  4.87 0.51 1.81 1.64 0.91 3.11 0.45 0.49 4.56 0.48 ...
 $ Estudinte: chr  "Andrea" "Nicolas" "Nicolas" "Esteban" ...


In [176]:
nrow(datos.df2)
ncol(datos.df2)
dim(datos.df2)

[1] 11

[1] 3

[1] 11  3

In [178]:
nrow(x)
length(x)
NROW(x)

NULL

[1] 11

[1] 11

In [187]:
head(datos.df2, n=3)
tail(datos.df2, n=2)

Materias Notas Estudinte
1      micro  4.87    Andrea
2      macro  0.51   Nicolas
3 desarrollo  1.81   Nicolas

Materias Notas Estudinte
10 econometria  0.48   Nicolas
11        <NA>  1.48     Laura

In [189]:
datos.df2[1:3, ]

Materias Notas Estudinte
1      micro  4.87    Andrea
2      macro  0.51   Nicolas
3 desarrollo  1.81   Nicolas

In [207]:
datos.df2[ , 3 ]
class(datos.df2[ , 3 ])

[1] "Andrea"  "Nicolas" "Nicolas" "Esteban" "Nicolas" "Laura"   "Laura"  
 [8] "Laura"   "Laura"   "Nicolas" "Laura"

[1] "character"

In [208]:
datos.df2[ , 3 , drop=F]
class(datos.df2[ , 3 , drop=F])

Estudinte
1     Andrea
2    Nicolas
3    Nicolas
4    Esteban
5    Nicolas
6      Laura
7      Laura
8      Laura
9      Laura
10   Nicolas
11     Laura

[1] "data.frame"

In [194]:
datos.df2[ 1:3 , 3 , drop= F]

Estudinte
1    Andrea
2   Nicolas
3   Nicolas

In [196]:
datos.df2[ 3:9 , 1:2]

Materias Notas
3 desarrollo  1.81
4       <NA>  1.64
5      micro  0.91
6    calculo  3.11
7   dinamica  0.45
8   historia  0.49
9 desarrollo  4.56

In [197]:
datos.df2[ c(3, 9) , 1:2]

Materias Notas
3 desarrollo  1.81
9 desarrollo  4.56

In [200]:
datos.df[ c('id-5', 'id-9') , 1:2]

Materias Notas
id-5      micro  0.91
id-9 desarrollo  4.56

In [202]:
datos.df2[ , -3]

Materias Notas
1        micro  4.87
2        macro  0.51
3   desarrollo  1.81
4         <NA>  1.64
5        micro  0.91
6      calculo  3.11
7     dinamica  0.45
8     historia  0.49
9   desarrollo  4.56
10 econometria  0.48
11        <NA>  1.48

In [209]:
datos.df2[ , 'Notas', drop=F]

Notas
1   4.87
2   0.51
3   1.81
4   1.64
5   0.91
6   3.11
7   0.45
8   0.49
9   4.56
10  0.48
11  1.48

In [213]:
datos.df2["Notas"]
class(datos.df2["Notas"])

Notas
1   4.87
2   0.51
3   1.81
4   1.64
5   0.91
6   3.11
7   0.45
8   0.49
9   4.56
10  0.48
11  1.48

[1] "data.frame"

In [212]:
datos.df2[["Notas"]]
class(datos.df2[["Notas"]])

[1] 4.87 0.51 1.81 1.64 0.91 3.11 0.45 0.49 4.56 0.48 1.48

[1] "numeric"

In [204]:
datos.df2[ , c('Materias', 'Estudinte')]

Materias Estudinte
1        micro    Andrea
2        macro   Nicolas
3   desarrollo   Nicolas
4         <NA>   Esteban
5        micro   Nicolas
6      calculo     Laura
7     dinamica     Laura
8     historia     Laura
9   desarrollo     Laura
10 econometria   Nicolas
11        <NA>     Laura

### Listas

In [215]:
Lista1 <- list(1, 2, 3)
Lista1

[[1]]
[1] 1

[[2]]
[1] 2

[[3]]
[1] 3

In [217]:
Lista2 <- list(c(1, 2, 3))
Lista2

[[1]]
[1] 1 2 3

In [223]:
Lista3 <- list(c(1, 2, 3), seq(1, 20, 2))
Lista3

[[1]]
[1] 1 2 3

[[2]]
 [1]  1  3  5  7  9 11 13 15 17 19

In [235]:
Lista4 <- list(datos.df, datos.df2)
print(Lista4)

[[1]]
         Materias Notas Estudiante
id-1        micro  4.87     Andrea
id-2        macro  0.51    Nicolas
id-3   desarrollo  1.81    Nicolas
id-4         <NA>  1.64    Esteban
id-5        micro  0.91    Nicolas
id-6      calculo  3.11      Laura
id-7     dinamica  0.45      Laura
id-8     historia  0.49      Laura
id-9   desarrollo  4.56      Laura
id-10 econometria  0.48    Nicolas
id-11        <NA>  1.48      Laura

[[2]]
      Materias Notas Estudinte
1        micro  4.87    Andrea
2        macro  0.51   Nicolas
3   desarrollo  1.81   Nicolas
4         <NA>  1.64   Esteban
5        micro  0.91   Nicolas
6      calculo  3.11     Laura
7     dinamica  0.45     Laura
8     historia  0.49     Laura
9   desarrollo  4.56     Laura
10 econometria  0.48   Nicolas
11        <NA>  1.48     Laura



In [234]:
Lista5 <- list(datos.df, Lista3, x)
names(Lista5) <- c('Datos', 'Secuencias', 'Notas')
print(Lista5)

$Datos
         Materias Notas Estudiante
id-1        micro  4.87     Andrea
id-2        macro  0.51    Nicolas
id-3   desarrollo  1.81    Nicolas
id-4         <NA>  1.64    Esteban
id-5        micro  0.91    Nicolas
id-6      calculo  3.11      Laura
id-7     dinamica  0.45      Laura
id-8     historia  0.49      Laura
id-9   desarrollo  4.56      Laura
id-10 econometria  0.48    Nicolas
id-11        <NA>  1.48      Laura

$Secuencias
$Secuencias[[1]]
[1] 1 2 3

$Secuencias[[2]]
 [1]  1  3  5  7  9 11 13 15 17 19


$Notas
 [1] 4.87 0.51 1.81 1.64 0.91 3.11 0.45 0.49 4.56 0.48 1.48



In [233]:
Lista6 <- list(Datos=datos.df, Secuencias=Lista3, Notas=x)
print(Lista6)

$Datos
         Materias Notas Estudiante
id-1        micro  4.87     Andrea
id-2        macro  0.51    Nicolas
id-3   desarrollo  1.81    Nicolas
id-4         <NA>  1.64    Esteban
id-5        micro  0.91    Nicolas
id-6      calculo  3.11      Laura
id-7     dinamica  0.45      Laura
id-8     historia  0.49      Laura
id-9   desarrollo  4.56      Laura
id-10 econometria  0.48    Nicolas
id-11        <NA>  1.48      Laura

$Secuencias
$Secuencias[[1]]
[1] 1 2 3

$Secuencias[[2]]
 [1]  1  3  5  7  9 11 13 15 17 19


$Notas
 [1] 4.87 0.51 1.81 1.64 0.91 3.11 0.45 0.49 4.56 0.48 1.48



In [230]:
ListaVacia <- vector(mode='list', length=3)
ListaVacia

[[1]]
NULL

[[2]]
NULL

[[3]]
NULL

In [232]:
ListaVacia[[1]] <- datos.df
print(ListaVacia)

[[1]]
         Materias Notas Estudiante
id-1        micro  4.87     Andrea
id-2        macro  0.51    Nicolas
id-3   desarrollo  1.81    Nicolas
id-4         <NA>  1.64    Esteban
id-5        micro  0.91    Nicolas
id-6      calculo  3.11      Laura
id-7     dinamica  0.45      Laura
id-8     historia  0.49      Laura
id-9   desarrollo  4.56      Laura
id-10 econometria  0.48    Nicolas
id-11        <NA>  1.48      Laura

[[2]]
NULL

[[3]]
NULL



In [237]:
ListaVacia[[1]]$Estudiante

[1] Andrea  Nicolas Nicolas Esteban Nicolas Laura   Laura   Laura   Laura  
[10] Nicolas Laura  
Levels: Andrea Esteban Laura Nicolas

### Matrices

Cada Elemento debe se del mismo tipo

In [242]:
M <- matrix(1:20, nrow=5)
print(M)

     [,1] [,2] [,3] [,4]
[1,]    1    6   11   16
[2,]    2    7   12   17
[3,]    3    8   13   18
[4,]    4    9   14   19
[5,]    5   10   15   20


In [243]:
nrow(M)
ncol(M)
dim(M)

[1] 5

[1] 4

[1] 5 4

In [244]:
K <- matrix(rnorm(20), ncol=4)
print(K)

            [,1]        [,2]       [,3]       [,4]
[1,]  0.24170557  0.64216113 -0.2794472 -2.5798735
[2,]  0.52387464  0.40524826  1.2026844  0.7691884
[3,]  0.04801921  1.74727397  1.3728459  2.1923392
[4,]  0.27746892 -0.07027668  0.2221622  1.1927714
[5,] -0.81551314 -0.32461034 -0.2715377  0.7019765


In [248]:
print(M + K)

         [,1]     [,2]     [,3]     [,4]
[1,] 1.241706 6.642161 10.72055 13.42013
[2,] 2.523875 7.405248 13.20268 17.76919
[3,] 3.048019 9.747274 14.37285 20.19234
[4,] 4.277469 8.929723 14.22216 20.19277
[5,] 4.184487 9.675390 14.72846 20.70198


In [249]:
print(M*K)

           [,1]       [,2]      [,3]      [,4]
[1,]  0.2417056  3.8529668 -3.073919 -41.27798
[2,]  1.0477493  2.8367378 14.432213  13.07620
[3,]  0.1440576 13.9781917 17.846996  39.46211
[4,]  1.1098757 -0.6324901  3.110271  22.66266
[5,] -4.0775657 -3.2461034 -4.073066  14.03953


In [252]:
nrow(M)
ncol(K)

[1] 5

[1] 4

In [257]:
print(t(K))
ncol(t(K))
nrow(M)==ncol(t(K))

           [,1]      [,2]       [,3]        [,4]       [,5]
[1,]  0.2417056 0.5238746 0.04801921  0.27746892 -0.8155131
[2,]  0.6421611 0.4052483 1.74727397 -0.07027668 -0.3246103
[3,] -0.2794472 1.2026844 1.37284586  0.22216219 -0.2715377
[4,] -2.5798735 0.7691884 2.19233921  1.19277142  0.7019765


[1] 5

[1] TRUE

In [251]:
print(M%*%t(K))

          [,1]     [,2]     [,3]     [,4]     [,5]
[1,] -40.25722 28.49191 60.71039 21.38394 5.481533
[2,] -42.23268 31.39290 66.07087 23.00606 4.771849
[3,] -44.20813 34.29390 71.43135 24.62819 4.062164
[4,] -46.18358 37.19489 76.79183 26.25031 3.352479
[5,] -48.15904 40.09589 82.15231 27.87244 2.642794


In [260]:
colnames(M) <- LETTERS[1:4]
rownames(M) <- letters[1:5]
print(M)

  A  B  C  D
a 1  6 11 16
b 2  7 12 17
c 3  8 13 18
d 4  9 14 19
e 5 10 15 20


### Arrays

Número arbitrario de dimensiones

In [5]:
array <- array(1:24 , dim=c(2, 4, 3))
print(array)

, , 1

     [,1] [,2] [,3] [,4]
[1,]    1    3    5    7
[2,]    2    4    6    8

, , 2

     [,1] [,2] [,3] [,4]
[1,]    9   11   13   15
[2,]   10   12   14   16

, , 3

     [,1] [,2] [,3] [,4]
[1,]   17   19   21   23
[2,]   18   20   22   24



In [7]:
print(array[1, , ])

     [,1] [,2] [,3]
[1,]    1    9   17
[2,]    3   11   19
[3,]    5   13   21
[4,]    7   15   23


In [8]:
print(array[, 1, 1])

[1] 1 2


### 2. Entrada de datos

### Leer CSV

In [10]:
getwd()

[1] "C:/Users/acer/GITHUB"

In [34]:
IACT <- read.table('IACT.csv', 
                   sep=';', 
                   skip= 4, 
                   header=T, 
                   nrow= 7)

In [35]:
head(IACT)

País X1995 X1996 X1997 X1998 X1999 X2000 X2001 X2002 X2003 X2004 X2005
1 Argentina 0,49% 0,50% 0,50% 0,50% 0,52% 0,50% 0,48% 0,44% 0,46% 0,49% 0,53%
2    Brasil  n.d.  n.d.  n.d.  n.d.  n.d. 1,30% 1,33% 1,30% 1,26% 1,24% 1,27%
3  Colombia 0,55% 0,56% 0,53% 0,32%  n.d. 0,31% 0,28% 0,31% 0,35% 0,40% 0,42%
4      Cuba 0,87% 0,78% 0,82% 0,93% 1,01% 0,89% 0,98% 0,88% 0,94% 0,93% 0,84%
5    México 0,35% 0,35% 0,42% 0,46% 0,41% 0,42% 0,41% 0,39% 0,39% 0,33% 0,34%
6 Venezuela 0,61% 0,45% 0,43% 0,39% 0,39% 0,38% 0,50% 0,43% 0,31% 0,25% 0,35%
  X2006 X2007 X2008 X2009 X2010 X2011
1 0,58% 0,61% 0,61% 0,67% 0,70% 0,73%
2 1,29% 1,40% 1,45% 1,57% 1,62% 1,64%
3 0,38% 0,44% 0,47% 0,44% 0,46% 0,47%
4 0,69% 0,72% 0,83% 1,02% 1,01% 0,45%
5 0,32% 0,32% 0,36% 0,39% 0,42% 0,41%
6 1,78% 2,69% 2,54% 2,36%  n.d.  n.d.

In [50]:
IACT <- read.table('IACT.csv', sep=';', skip= 4, header=T, nrow= 7, stringsAsFactors=T,
                   na.strings=c('n.d.', 'NA'))


In [51]:
head(IACT)

País X1995 X1996 X1997 X1998 X1999 X2000 X2001 X2002 X2003 X2004 X2005
1 Argentina 0,49% 0,50% 0,50% 0,50% 0,52% 0,50% 0,48% 0,44% 0,46% 0,49% 0,53%
2    Brasil  <NA>  <NA>  <NA>  <NA>  <NA> 1,30% 1,33% 1,30% 1,26% 1,24% 1,27%
3  Colombia 0,55% 0,56% 0,53% 0,32%  <NA> 0,31% 0,28% 0,31% 0,35% 0,40% 0,42%
4      Cuba 0,87% 0,78% 0,82% 0,93% 1,01% 0,89% 0,98% 0,88% 0,94% 0,93% 0,84%
5    México 0,35% 0,35% 0,42% 0,46% 0,41% 0,42% 0,41% 0,39% 0,39% 0,33% 0,34%
6 Venezuela 0,61% 0,45% 0,43% 0,39% 0,39% 0,38% 0,50% 0,43% 0,31% 0,25% 0,35%
  X2006 X2007 X2008 X2009 X2010 X2011
1 0,58% 0,61% 0,61% 0,67% 0,70% 0,73%
2 1,29% 1,40% 1,45% 1,57% 1,62% 1,64%
3 0,38% 0,44% 0,47% 0,44% 0,46% 0,47%
4 0,69% 0,72% 0,83% 1,02% 1,01% 0,45%
5 0,32% 0,32% 0,36% 0,39% 0,42% 0,41%
6 1,78% 2,69% 2,54% 2,36%  <NA>  <NA>

In [52]:
summary(IACT)

                         País     X1995     X1996     X1997     X1998  
 América Latina y el Caribe:1   0,35%:1   0,35%:1   0,42%:1   0,32%:1  
 Argentina                 :1   0,49%:1   0,45%:1   0,43%:1   0,39%:1  
 Brasil                    :1   0,55%:1   0,50%:1   0,50%:1   0,46%:1  
 Colombia                  :1   0,61%:1   0,56%:1   0,53%:1   0,50%:1  
 Cuba                      :1   0,87%:1   0,78%:1   0,78%:1   0,93%:1  
 México                    :1   0,93%:1   0,93%:1   0,82%:1   0,97%:1  
 Venezuela                 :1   NA's :1   NA's :1   NA's :1   NA's :1  
   X1999     X2000     X2001     X2002     X2003     X2004     X2005  
 0,39%:1   0,31%:1   0,28%:1   0,31%:1   0,31%:1   0,25%:1   0,34%:1  
 0,41%:1   0,38%:1   0,41%:1   0,39%:1   0,35%:1   0,33%:1   0,35%:1  
 0,52%:1   0,42%:1   0,48%:1   0,43%:1   0,39%:1   0,40%:1   0,42%:1  
 0,74%:1   0,50%:1   0,50%:1   0,44%:1   0,46%:1   0,49%:1   0,53%:1  
 1,01%:1   0,73%:1   0,71%:1   0,70%:1   0,68%:1   0,67%:1   0,72%:1 

In [ ]:
Discusión de stringAsfactors

Discusión entre read.table y read.csv

In [ ]:
Discusión entre read.csv2 y read.csv

In [ ]:
Paquetes para leer excel

In [ ]:
Conexiones ODBC

In [ ]:
Tratameinbto de bases de datos

In [ ]:
rio

Infiere la estructura de datos de nuestros archivos

In [18]:
library(rio)

Warning message:
: package 'rio' was built under R version 3.2.3

In [54]:
rio <- import()

ERROR: Error in fread(input = file, sep = sep, sep2 = "auto", header = header, : 


In [ ]:
Scraping sobre wed fundamentos

### Ejemplo: Indicadores de desarrollo

In [61]:
#download.file("http://databank.worldbank.org/data/download/WDI_csv.zip", "WDI_csv.zip")
#unzip("WDI_csv.zip")

In [62]:
wdistats <- read.csv("WDI_Data.csv")
head(wdistats)

Country.Name Country.Code
1  Afghanistan          AFG
2  Afghanistan          AFG
3  Afghanistan          AFG
4  Afghanistan          AFG
5  Afghanistan          AFG
6  Afghanistan          AFG
                                                             Indicator.Name
1                 2005 PPP conversion factor, GDP (LCU per international $)
2 2005 PPP conversion factor, private consumption (LCU per international $)
3                                   Access to electricity (% of population)
4                      Access to electricity, rural (% of rural population)
5                      Access to electricity, urban (% of urban population)
6                                Access to non-solid fuel (% of population)
     Indicator.Code X1960 X1961 X1962 X1963 X1964 X1965 X1966 X1967 X1968 X1969
1     PA.NUS.PPP.05    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2 PA.NUS.PRVT.PP.05    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
3    EG.ELC.ACCS.ZS    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
4 EG.ELC.ACCS.RU.ZS    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
5 EG.ELC.ACCS.UR.ZS    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
6    EG.NSF.ACCS.ZS    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
  X1970 X1971 X1972 X1973 X1974 X1975 X1976 X1977 X1978 X1979 X1980 X1981 X1982
1    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
2    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
3    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
4    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
5    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
6    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA    NA
  X1983 X1984 X1985 X1986 X1987 X1988 X1989     X1990 X1991 X1992 X1993 X1994
1    NA    NA    NA    NA    NA    NA    NA        NA    NA    NA    NA    NA
2    NA    NA    NA    NA    NA    NA    NA        NA    NA    NA    NA    NA
3    NA    NA    NA    NA    NA    NA    NA 34.615670    NA    NA    NA    NA
4    NA    NA    NA    NA    NA    NA    NA 20.360110    NA    NA    NA    NA
5    NA    NA    NA    NA    NA    NA    NA 98.872860    NA    NA    NA    NA
6    NA    NA    NA    NA    NA    NA    NA  4.111767    NA    NA    NA    NA
  X1995 X1996 X1997 X1998 X1999    X2000 X2001 X2002 X2003 X2004    X2005 X2006
1    NA    NA    NA    NA    NA       NA    NA    NA    NA    NA 15.13216    NA
2    NA    NA    NA    NA    NA       NA    NA    NA    NA    NA 16.70967    NA
3    NA    NA    NA    NA    NA 37.45584    NA    NA    NA    NA       NA    NA
4    NA    NA    NA    NA    NA 24.28065    NA    NA    NA    NA       NA    NA
5    NA    NA    NA    NA    NA 88.29071    NA    NA    NA    NA       NA    NA
6    NA    NA    NA    NA    NA 13.70856    NA    NA    NA    NA       NA    NA
  X2007 X2008 X2009    X2010 X2011    X2012 X2013 X2014 X2015
1    NA    NA    NA       NA    NA       NA    NA    NA    NA
2    NA    NA    NA       NA    NA       NA    NA    NA    NA
3    NA    NA    NA 41.00000    NA 43.00000    NA    NA    NA
4    NA    NA    NA 29.00000    NA 32.00000    NA    NA    NA
5    NA    NA    NA 80.63733    NA 83.00000    NA    NA    NA
6    NA    NA    NA 18.61123    NA 19.48096    NA    NA    NA